exports.tasksPage = function(tasks, max, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-light-blue">
                    <h2>Notes</h2>
                </header>

                <form action="/tasks/registo" class="w3-container  w3-center w3-margin" method="POST">
                    <input type="hidden" name="id" value=${max}>
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round" ><b>Description</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="what">
                 
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round" ><b>Responsible</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="who">

                    <label><p class="w3-2021-amethyst-orchid w3-round"><b>Deadline</b></p></label>
                    <input class="w3-input w3-border w3-round w3-center" type="date" name="deadline">
                    
                    <button class="w3-btn w3-light-blue w3-round w3-2021-amethyst-orchid w3-margin-top" type="submit">Submit</button>
                </form>
                <footer class="w3-container w3-light-blue">
                    <h5>Generated by ME in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
                `
    return pagHTML
}