exports.tasksPage = function(tasks, max, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>To Do List</title>
        </head>
        <body>
        <main class="w3-center">
            <div class="w3-card-4">
                <header class="w3-container w3-light-blue">
                    <h2>To Do List</h2>
                </header>

                <form action="/tasks/registo" class="w3-container  w3-center w3-margin" method="POST">
                    <input type="hidden" name="id" value=${max}>
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round" ><b>Description</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="what">
                 
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round" ><b>Responsible</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="who">

                    <label><p class="w3-2021-amethyst-orchid w3-round"><b>Deadline</b></p></label>
                    <input class="w3-input w3-border w3-round w3-center" type="date" name="deadline">
                    
                    <button class="w3-btn w3-light-blue w3-round w3-2021-amethyst-orchid w3-margin-top" type="submit">Submit</button>
                </form>
            </div>

            <div class="w3-row w3-border">
                <div class="w3-container w3-half w3-card-4 w3-margin-top w3-light-blue"><h3>Tasks to be done</h3></div>
                <div class="w3-container w3-half w3-card-4 w3-margin-top w3-light-blue"><h3>Completed Tasks</h3></div>
            </div>
            <div class="w3-row w3-border">
                <div class="w3-container w3-half">
                `
                for(let i = 0; i < tasks.length; i++) {
                    if(!("done" in tasks[i])){
                        pagHTML +=`
                            <ul class="w3-ul w3-card-4">
                                <li><b>Description:</b> ${tasks[i].what}</li>
                                <li><b>Responsible:</b> ${tasks[i].who}</li>
                                <li><b>DeadLine:</b> ${tasks[i].deadline}</li>
                                <li>[<a href="/tasks/edit/${tasks[i].id}">Edit</a>] [<a href="/tasks/done/${tasks[i].id}">Done</a>]</li>
                            </ul>
                        `
                    }
                }
   pagHTML +=`
                </div>
                <div class="w3-container w3-half">    
                `
                for(let i = 0; i < tasks.length; i++) {
                    if(("done" in tasks[i])){    
                        pagHTML +=`
                            <ul class="w3-ul w3-card-4">
                                <li><b>Description:</b> ${tasks[i].what}</li>
                                <li><b>Responsible:</b> ${tasks[i].who}</li>
                                <li><b>DeadLine:</b> ${tasks[i].deadline}</li>
                            </ul>
                        `
                    }
                    
                }
  pagHTML +=`
                </div>
            </div>


            <footer class="w3-container w3-light-blue">
                <h5>Generated by ME in ${d}</h5>
            </footer>
            </main>
            </body>
    </html>
                `
    return pagHTML
}

exports.taskFormEditPage = function(task, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Edit Task Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-light-blue">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container w3-center w3-margin" method="POST">
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round"  ><b>Task Description</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="what" value="${task.what}">
                     
                    <label><p class="w3-2021-amethyst-orchid w3-center w3-round"  ><b>Responsible</b></p></label>
                    <input class="w3-input w3-border w3-margin-bottom w3-center w3-round" type="text" name="who" value="${task.who}">
                      
                    <label><p class="w3-2021-amethyst-orchid w3-round"><b>Due date</b></p></label>
                    <input class="w3-input w3-border w3-round w3-center" type="date" name="deadline" value=${task.deadline}>
                    
                    <button class="w3-btn w3-round w3-2021-amethyst-orchid w3-margin-top" type="submit">Change</button>
                     
                    </form>

                <footer class="w3-container w3-light-blue">
                    <h5>Generated by ME in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
    return pagHTML
}